sonar.projectKey=ynraws_securebank-platform
sonar.projectName=SecureBank Platform
sonar.projectVersion=1.0

# Source directories
sonar.sources=.
sonar.exclusions=**/vendor/**,**/node_modules/**,**/*.test.go,**/*_test.go,**/target/**,**/__pycache__/**

# Language specific
sonar.go.coverage.reportPaths=coverage.out
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8
sonar.organization=ynraws
