apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-svc
  namespace: securebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-svc
  template:
    metadata:
      labels:
        app: account-svc
    spec:
      containers:
        - name: account-svc
          image: ynraws/securebank-account-svc:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: account-svc
  namespace: securebank
spec:
  selector:
    app: account-svc
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
