apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-reporter
  namespace: securebank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-reporter
  template:
    metadata:
      labels:
        app: cost-reporter
    spec:
      containers:
        - name: cost-reporter
          image: itsmeynr/securebank-cost-reporter:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: cost-reporter
  namespace: securebank
spec:
  selector:
    app: cost-reporter
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
