apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securebank-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ynraws/securebank-platform
    targetRevision: HEAD
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: securebank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
